/*
 * =============================================================================
 * GENERATED BY MAPSTRUCT, THEN COMMITTED ON PURPOSE. DO NOT EDIT BY HAND.
 * =============================================================================
 *
 * This file is the output of mapstruct-processor 1.6.3 run against
 * ExchangePayloadMapper. It lives in src/main/java rather than being regenerated
 * on every build, and the processor is NOT on the normal build's annotation
 * processor path.
 *
 * Why:
 *   Running the processor as part of the build corrupted roughly HALF of all
 *   compilations. MapStruct emits this source in one annotation-processing round
 *   and javac attributes it in the next, and about one run in two the resulting
 *   class file came out with unresolved symbols - the `implements
 *   ExchangePayloadMapper` clause dropped, and method descriptors stripped of
 *   their package qualifiers (`LSymbolNormalizer;` instead of
 *   `Lcom/mdg/gateway/mapper/SymbolNormalizer;`).
 *
 *   Nothing reported an error. The build printed BUILD SUCCESS and the damage
 *   surfaced later as NoSuchMethodError, or JUnit refusing to discover tests with
 *   a NoClassDefFoundError naming a class that plainly exists.
 *
 *   Measured 8/16 corrupt on JDK 21 and 6/6 inside a Linux container on the same
 *   JDK. Reproduced with and without Lombok, on maven-compiler-plugin 3.13.0 and
 *   3.14.1, forked and in-process, with release=21 and release=24, and with a
 *   toolchain (which made it worse). The generated SOURCE was always correct -
 *   only its compilation raced. Compiling it as an ordinary source file, with no
 *   processor round involved, is deterministic.
 *
 * To regenerate after changing ExchangePayloadMapper:
 *
 *   mvn -Pregenerate-mappers clean generate-sources
 *   cp target/generated-sources/annotations/com/mdg/gateway/mapper/ExchangePayloadMapperImpl.java \
 *      src/main/java/com/mdg/gateway/mapper/
 *   # then re-add this header, and run `make verify`
 *
 * Drift between the interface and this class is caught by
 * ExchangePayloadMapperTest, which asserts every canonical field for all three
 * venues. If you change the interface and forget to regenerate, those tests fail.
 */
package com.mdg.gateway.mapper;

import com.mdg.gateway.dto.BinanceTradePayload;
import com.mdg.gateway.dto.CoinbaseTickerPayload;
import com.mdg.gateway.dto.KrakenTradePayload;
import com.mdg.gateway.model.CanonicalTradeEvent;
import javax.annotation.processing.Generated;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2026-09-23T11:55:12+0530",
    comments = "version: 1.6.3, compiler: javac, environment: Java 21.0.12.1 (Homebrew)"
)
@Component
public class ExchangePayloadMapperImpl implements ExchangePayloadMapper {

    private final SymbolNormalizer symbolNormalizer;

    @Autowired
    public ExchangePayloadMapperImpl(SymbolNormalizer symbolNormalizer) {

        this.symbolNormalizer = symbolNormalizer;
    }

    @Override
    public CanonicalTradeEvent fromBinance(BinanceTradePayload payload, String rawPayload) {
        if ( payload == null && rawPayload == null ) {
            return null;
        }

        CanonicalTradeEvent.Builder canonicalTradeEvent = CanonicalTradeEvent.builder();

        if ( payload != null ) {
            canonicalTradeEvent.symbol( symbolNormalizer.normalizeConcatenated( payload.symbol() ) );
            canonicalTradeEvent.price( payload.price() );
            canonicalTradeEvent.quantity( payload.quantity() );
            canonicalTradeEvent.timestamp( epochMillisToInstant( payload.tradeTime() ) );
        }
        canonicalTradeEvent.rawPayload( rawPayload );
        canonicalTradeEvent.eventId( newEventId() );
        canonicalTradeEvent.exchange( "BINANCE" );

        return canonicalTradeEvent.build();
    }

    @Override
    public CanonicalTradeEvent fromCoinbase(CoinbaseTickerPayload payload, String rawPayload) {
        if ( payload == null && rawPayload == null ) {
            return null;
        }

        CanonicalTradeEvent.Builder canonicalTradeEvent = CanonicalTradeEvent.builder();

        if ( payload != null ) {
            canonicalTradeEvent.symbol( symbolNormalizer.normalizeDelimited( payload.productId() ) );
            canonicalTradeEvent.price( payload.price() );
            canonicalTradeEvent.quantity( payload.volume24h() );
            canonicalTradeEvent.timestamp( payload.timestamp() );
        }
        canonicalTradeEvent.rawPayload( rawPayload );
        canonicalTradeEvent.eventId( newEventId() );
        canonicalTradeEvent.exchange( "COINBASE" );

        return canonicalTradeEvent.build();
    }

    @Override
    public CanonicalTradeEvent fromKraken(KrakenTradePayload payload, String rawPayload) {
        if ( payload == null && rawPayload == null ) {
            return null;
        }

        CanonicalTradeEvent.Builder canonicalTradeEvent = CanonicalTradeEvent.builder();

        if ( payload != null ) {
            canonicalTradeEvent.symbol( symbolNormalizer.normalizeDelimited( payload.symbol() ) );
            canonicalTradeEvent.price( payload.price() );
            canonicalTradeEvent.quantity( payload.quantity() );
            canonicalTradeEvent.timestamp( payload.timestamp() );
        }
        canonicalTradeEvent.rawPayload( rawPayload );
        canonicalTradeEvent.eventId( newEventId() );
        canonicalTradeEvent.exchange( "KRAKEN" );

        return canonicalTradeEvent.build();
    }
}
